// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4qEAAhTAlWyEP0_OBmtm-2z6JsQ1fW00',
    appId: '1:662434970814:web:97c8ad2872f16d52b972ef',
    messagingSenderId: '662434970814',
    projectId: 'group-study-matcher',
    authDomain: 'group-study-matcher.firebaseapp.com',
    storageBucket: 'group-study-matcher.appspot.com',
    measurementId: 'G-Y0Z9KJFKLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5y8tYKI-EUKjU3t4fzMxb2TMFwbcaM_k',
    appId: '1:662434970814:android:92ac33bf937eaebbb972ef',
    messagingSenderId: '662434970814',
    projectId: 'group-study-matcher',
    storageBucket: 'group-study-matcher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS3XkjtUObSsqXqPn0cLTQPIZsp4QN7Lc',
    appId: '1:662434970814:ios:270cae4189e29fbcb972ef',
    messagingSenderId: '662434970814',
    projectId: 'group-study-matcher',
    storageBucket: 'group-study-matcher.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS3XkjtUObSsqXqPn0cLTQPIZsp4QN7Lc',
    appId: '1:662434970814:ios:270cae4189e29fbcb972ef',
    messagingSenderId: '662434970814',
    projectId: 'group-study-matcher',
    storageBucket: 'group-study-matcher.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
